# Generated by Django 5.2.3 on 2025-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0003_courseresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='full_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
