# Generated by Django 5.2.3 on 2025-06-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0004_schedule_full_end_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='full_end_datetime',
        ),
    ]
